fetch data from noco db
esc-chula/intania-form pull request #1
Opened 2024-08-23 12:40 UTC by neennera

- clean fetcher ให้โค้ดสั้นขึ้น
- url เป็นแบบ ‘/form/form-name” ลอง “form/regis-test” ได้
- เปลี่ยน getNocoID ให้รับ input เป็น name
- getNocoID return เป็น object formID, ไม่ก็ res error
- เช็คแต่ละ field ให้ไม่เป็น “”, ให้เว็บแสดง error msg แบบ alert

2024-08-26 18:09 UTC, neennera commented on package.json
> +    "react-router-dom": "^6.26.1",
แค่เอาใส่แล้วไม่ใช่แต่ลืมเอาออกค่ะ5555

2024-08-27 14:44 UTC, shalluv commented on package-lock.json
@neennera seem like this file has not removed yet.

2024-08-27 15:12 UTC, shalluv requested changes

2024-08-27 15:12 UTC, shalluv commented on src/providers/form-provider.tsx
> +import { Form } from '@/types/form'
is this resolved?

2024-08-28 15:16 UTC, shalluv approved these changes

2024-08-28 15:23 UTC, merged